version: '3.8'
services:
  app:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongoData:/data/db
    ports:
      - "27018:27017"

  client:
    build: ./kanban-react
    ports:
      - "3000:3000"
    volumes:
      - ./kanban-react:/app
      - /app/node_modules
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongoData: