# Choix de l'image de base
FROM node:latest

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de configuration
COPY package*.json ./

# Installation des dépendances
RUN npm install

# Copier le reste des fichiers
COPY . .

# Exposer le port sur lequel l'application Express écoute
EXPOSE 3001

# Commande pour démarrer l'application
CMD ["npm", "run", "dev"]